name: Manually copy photos
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  copyPhotos:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
      - run: pip install dropbox
      - run: pip install posixpath
        env: 
          DROPBOX_KEY: ${{ secrets.DROPBOX_KEY }}
      - run: python3 main.py 